SELECT Y.CART_ID
FROM
    (
    SELECT  CART_ID
    FROM CART_PRODUCTS
    WHERE NAME ='Yogurt' 
    GROUP BY 1
    ) AS Y 
    INNER JOIN CART_PRODUCTS AS M ON Y.CART_ID = M.CART_ID
WHERE NAME ='Milk'
GROUP BY 1
ORDER BY 1;