SELECT
    C.CAR_ID, 
    C.CAR_TYPE, 
    TRUNCATE(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100), 0) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR AS C 
    LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON C.CAR_TYPE = P.CAR_TYPE AND DURATION_TYPE = '30일 이상'
WHERE
    C.CAR_TYPE IN ('세단', 'SUV') AND
    C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100) >= 500000 AND
    C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100) < 2000000 AND
    C.CAR_ID NOT IN
    (SELECT 
        CAR_ID 
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        (START_DATE LIKE '2022-11-%' OR END_DATE LIKE '2022-11-%')
        OR
        (START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-30'))
ORDER BY 
    3 DESC, 2, 1 DESC;