SELECT ANIMAL_ID,ANIMAL_TYPE,NAME
FROM
(
SELECT A.ANIMAL_ID,
       A.ANIMAL_TYPE,
       A.NAME,
       A.SEX_UPON_INTAKE,
       O.SEX_UPON_OUTCOME
FROM ANIMAL_INS AS A LEFT JOIN ANIMAL_OUTS AS O ON A.ANIMAL_ID = O.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE '%Intact%'
) T 
WHERE SEX_UPON_OUTCOME REGEXP 'Spayed|Neutered'
ORDER BY ANIMAL_ID ;