SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, UI.GENDER, COUNT(distinct UI.USER_ID) USERS
FROM ONLINE_SALE OS JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID
WHERE UI.GENDER IS NOT null
GROUP BY 1,2,3
ORDER BY 1,2,3;