SELECT FR.PRODUCT_ID, FR.PRODUCT_NAME, SUM(FR.PRICE*FO.AMOUNT)TOTAL_SALES
FROM FOOD_PRODUCT FR JOIN FOOD_ORDER FO 
     ON FR.PRODUCT_ID = FO.PRODUCT_ID
WHERE '2022-05-01' <= FO.PRODUCE_DATE AND FO.PRODUCE_DATE < '2022-06-01' 
GROUP BY 1
ORDER BY 3 DESC, 1 ASC;