
SELECT MONTH(START_DATE) as MONTH, CAR_ID, count(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                  WHERE START_DATE >= '2022-08-01' AND START_DATE <= '2022-10-31'
                  GROUP BY CAR_ID
                  HAVING count(*) >= 5)
    AND MONTH(START_DATE) >= 8 AND MONTH(START_DATE) <= 10
GROUP BY MONTH, CAR_ID
ORDER BY MONTH , CAR_ID DESC;