SELECT A.CATEGORY "CATEGORY", 
       SUM(B.SALES) "TOTAL_SALES"
FROM BOOK A INNER JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
WHERE B.SALES_DATE > '2021-12-31' AND B.SALES_DATE < '2022-02-01'
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY;